### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by bcr** [bplower/connect-snake#4]
It says I can play at http://connect-snake.brahmlower.io/ but that just goes to the top of the blog...

**Comment by brahmlower** [comment]
Yup, sites down at the moment- the whole brahmlower.io domain was hosted up on GKE a while back, but I ran out of credit and everything got shut down. I brought the blog back online in a quick-and-dirty fashion just to get it back up, but I neglected my various subdomains. I'll bring snake back online tonight though, 'cause it's kinda silly

**Comment by brahmlower** [comment]
Site's back up! Closing this issue, but feel free to open another if run into any other issues
